// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'datum.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Datum _$DatumFromJson(Map<String, dynamic> json) => Datum(
      id: (json['id'] as num?)?.toInt(),
      // catid: (json['catid'] as num?)?.toInt(),
      title: json['title'] as String?,
      // shorttitle: json['shorttitle'] as String?,
      logo: json['logo'] as String?,
      // cover: json['cover'] as String?,
      // openLink: json['open_link'] as String?,
      // version: json['version'] as String?,
      // digest: (json['digest'] as num?)?.toInt(),
      // recommend: (json['recommend'] as num?)?.toInt(),
      // favnum: (json['favnum'] as num?)?.toInt(),
      // ishp: (json['ishp'] as num?)?.toInt(),
      // ishot: (json['ishot'] as num?)?.toInt(),
      // isbiz: (json['isbiz'] as num?)?.toInt(),
      // iscps: (json['iscps'] as num?)?.toInt(),
      // isCoolapkCpa: (json['is_coolapk_cpa'] as num?)?.toInt(),
      // apktype: (json['apktype'] as num?)?.toInt(),
      // apkname: json['apkname'] as String?,
      // apkname2: json['apkname2'] as String?,
      apkversionname: json['apkversionname'] as String?,
      apkversioncode: (json['apkversioncode'] as num?)?.toInt(),
      // apklength: (json['apklength'] as num?)?.toInt(),
      apksize: json['apksize'] as String?,
      // apkmd5: json['apkmd5'] as String?,
      // sdkversion: (json['sdkversion'] as num?)?.toInt(),
      // romversion: json['romversion'] as String?,
      // hotlabel: json['hotlabel'] as String?,
      // shortlabel: json['shortlabel'] as String?,
      // keywords: json['keywords'] as String?,
      // description: json['description'] as String?,
      // developeruid: (json['developeruid'] as num?)?.toInt(),
      // developername: json['developername'] as String?,
      // star: (json['star'] as num?)?.toInt(),
      // score: json['score'] as String?,
      // adminscore: json['adminscore'] as String?,
      // downnum: (json['downnum'] as num?)?.toInt(),
      // follownum: (json['follownum'] as num?)?.toInt(),
      // votenum: (json['votenum'] as num?)?.toInt(),
      // commentnum: (json['commentnum'] as num?)?.toInt(),
      // replynum: (json['replynum'] as num?)?.toInt(),
      // commentBlockNum: (json['comment_block_num'] as num?)?.toInt(),
      // hotNum: (json['hot_num'] as num?)?.toInt(),
      // pubdate: (json['pubdate'] as num?)?.toInt(),
      // commentStatus: (json['comment_status'] as num?)?.toInt(),
      lastupdate: (json['lastupdate'] as num?)?.toInt(),
      // lastCommentUpdate: (json['last_comment_update'] as num?)?.toInt(),
      // isForumApp: (json['is_forum_app'] as num?)?.toInt(),
      // allowRating: (json['allow_rating'] as num?)?.toInt(),
      // getTimewitCpc: (json['get_timewit_cpc'] as num?)?.toInt(),
      // status: (json['status'] as num?)?.toInt(),
      // rtaCallback: json['rta_callback'] as String?,
      // entityType: json['entityType'] as String?,
      // entityId: (json['entityId'] as num?)?.toInt(),
      packageName: json['packageName'] as String?,
      // shortTags: json['shortTags'] as String?,
      // apkTypeName: json['apkTypeName'] as String?,
      // apkTypeUrl: json['apkTypeUrl'] as String?,
      // apkUrl: json['apkUrl'] as String?,
      // url: json['url'] as String?,
      // catDir: json['catDir'] as String?,
      // catName: json['catName'] as String?,
      // downCount: json['downCount'] as String?,
      // followCount: json['followCount'] as String?,
      // voteCount: (json['voteCount'] as num?)?.toInt(),
      // commentCount: json['commentCount'] as String?,
      // replyCount: (json['replyCount'] as num?)?.toInt(),
      // hotNumTxt: json['hot_num_txt'] as String?,
      // updateFlag: json['updateFlag'] as String?,
      // extraFlag: json['extraFlag'] as String?,
      // apkRomVersion: json['apkRomVersion'] as String?,
      // statusText: json['statusText'] as String?,
      // pubStatusText: json['pubStatusText'] as String?,
      // commentStatusText: json['commentStatusText'] as String?,
      // targetId: json['target_id'] as String?,
      // votescore: json['votescore'] as String?,
      // ratingStar: (json['rating_star'] as num?)?.toDouble(),
      changelog: json['changelog'] as String?,
      pkgBitType: (json['pkg_bit_type'] as num?)?.toInt(),
    );

Map<String, dynamic> _$DatumToJson(Datum instance) => <String, dynamic>{
      'id': instance.id,
      // 'catid': instance.catid,
      'title': instance.title,
      // 'shorttitle': instance.shorttitle,
      'logo': instance.logo,
      // 'cover': instance.cover,
      // 'open_link': instance.openLink,
      // 'version': instance.version,
      // 'digest': instance.digest,
      // 'recommend': instance.recommend,
      // 'favnum': instance.favnum,
      // 'ishp': instance.ishp,
      // 'ishot': instance.ishot,
      // 'isbiz': instance.isbiz,
      // 'iscps': instance.iscps,
      // 'is_coolapk_cpa': instance.isCoolapkCpa,
      // 'apktype': instance.apktype,
      // 'apkname': instance.apkname,
      // 'apkname2': instance.apkname2,
      'apkversionname': instance.apkversionname,
      'apkversioncode': instance.apkversioncode,
      // 'apklength': instance.apklength,
      'apksize': instance.apksize,
      // 'apkmd5': instance.apkmd5,
      // 'sdkversion': instance.sdkversion,
      // 'romversion': instance.romversion,
      // 'hotlabel': instance.hotlabel,
      // 'shortlabel': instance.shortlabel,
      // 'keywords': instance.keywords,
      // 'description': instance.description,
      // 'developeruid': instance.developeruid,
      // 'developername': instance.developername,
      // 'star': instance.star,
      // 'score': instance.score,
      // 'adminscore': instance.adminscore,
      // 'downnum': instance.downnum,
      // 'follownum': instance.follownum,
      // 'votenum': instance.votenum,
      // 'commentnum': instance.commentnum,
      // 'replynum': instance.replynum,
      // 'comment_block_num': instance.commentBlockNum,
      // 'hot_num': instance.hotNum,
      // 'pubdate': instance.pubdate,
      // 'comment_status': instance.commentStatus,
      // 'lastupdate': instance.lastupdate,
      // 'last_comment_update': instance.lastCommentUpdate,
      // 'is_forum_app': instance.isForumApp,
      // 'allow_rating': instance.allowRating,
      // 'get_timewit_cpc': instance.getTimewitCpc,
      // 'status': instance.status,
      // 'rta_callback': instance.rtaCallback,
      // 'entityType': instance.entityType,
      // 'entityId': instance.entityId,
      'packageName': instance.packageName,
      // 'shortTags': instance.shortTags,
      // 'apkTypeName': instance.apkTypeName,
      // 'apkTypeUrl': instance.apkTypeUrl,
      // 'apkUrl': instance.apkUrl,
      // 'url': instance.url,
      // 'catDir': instance.catDir,
      // 'catName': instance.catName,
      // 'downCount': instance.downCount,
      // 'followCount': instance.followCount,
      // 'voteCount': instance.voteCount,
      // 'commentCount': instance.commentCount,
      // 'replyCount': instance.replyCount,
      // 'hot_num_txt': instance.hotNumTxt,
      // 'updateFlag': instance.updateFlag,
      // 'extraFlag': instance.extraFlag,
      // 'apkRomVersion': instance.apkRomVersion,
      // 'statusText': instance.statusText,
      // 'pubStatusText': instance.pubStatusText,
      // 'commentStatusText': instance.commentStatusText,
      // 'target_id': instance.targetId,
      // 'votescore': instance.votescore,
      // 'rating_star': instance.ratingStar,
      'changelog': instance.changelog,
      'pkg_bit_type': instance.pkgBitType,
    };
